name: Android APK Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Java
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk-headless
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> "$GITHUB_ENV"

      - name: Test
        run: |
          java -version
          echo "ANDROID_HOME=$ANDROID_HOME"
